In [1]:
import numpy as np

In [9]:
arquivo = np.genfromtxt('test.txt', delimiter=",")
arquivo = arquivo.astype('int32')
print(arquivo)

arquivo > 50
arquivo  [arquivo > 50]

[[45 28 59 73 64 36 97 82 53 91 16]
 [75 61 19 33 29 78 72 80 48 68 55]
 [40 86 90 50 71 21 88 39 51 63 78]]


array([59, 73, 64, 97, 82, 53, 91, 75, 61, 78, 72, 80, 68, 55, 86, 90, 71,
       88, 51, 63, 78], dtype=int32)

In [ ]:
np.any(arquivo  > 30, axis= 0)

array([ True, False, False,  True, False, False,  True,  True,  True,
        True, False])

In [12]:
np.all(arquivo  > 30, axis= 0)

array([ True, False, False,  True, False, False,  True,  True,  True,
        True, False])

In [13]:
((arquivo > 10) & (arquivo < 50))

array([[ True,  True, False, False, False,  True, False, False, False,
        False,  True],
       [False, False,  True,  True,  True, False, False, False,  True,
        False, False],
       [ True, False, False, False, False,  True, False,  True, False,
        False, False]])

In [19]:
arquivo2 = np.genfromtxt("test2.txt", delimiter=",")
arquivo2 = arquivo2.astype('int32')
print(arquivo2)

[[62 35 84 57 46 71 11 68 53 79 29]
 [22 49 61 66 94 41 15 25 38 92 30]
 [76 56 77 27 65 87 52 39 80 47 33]]


In [21]:
arquivo3 = np.concatenate((arquivo, arquivo2), axis=0)
arquivo3

array([[45, 28, 59, 73, 64, 36, 97, 82, 53, 91, 16],
       [75, 61, 19, 33, 29, 78, 72, 80, 48, 68, 55],
       [40, 86, 90, 50, 71, 21, 88, 39, 51, 63, 78],
       [62, 35, 84, 57, 46, 71, 11, 68, 53, 79, 29],
       [22, 49, 61, 66, 94, 41, 15, 25, 38, 92, 30],
       [76, 56, 77, 27, 65, 87, 52, 39, 80, 47, 33]], dtype=int32)

In [29]:
np.savetxt("arquivo3.txt", arquivo3, fmt="%d", delimiter=",")

In [ ]:
arquivo4 = np.stack((arquivo, arquivo2))
arquivo5 = np.vstack((arquivo, arquivo2)) #vertical
arquivo6 = np.hstack((arquivo, arquivo2)) #horizontal

arquivo4
arquivo5
arquivo6

array([[45, 28, 59, 73, 64, 36, 97, 82, 53, 91, 16, 62, 35, 84, 57, 46,
        71, 11, 68, 53, 79, 29],
       [75, 61, 19, 33, 29, 78, 72, 80, 48, 68, 55, 22, 49, 61, 66, 94,
        41, 15, 25, 38, 92, 30],
       [40, 86, 90, 50, 71, 21, 88, 39, 51, 63, 78, 76, 56, 77, 27, 65,
        87, 52, 39, 80, 47, 33]], dtype=int32)

In [28]:
arquivo7 = np.split(arquivo3, 3, axis=0)
arquivo7

[array([[45, 28, 59, 73, 64, 36, 97, 82, 53, 91, 16],
        [75, 61, 19, 33, 29, 78, 72, 80, 48, 68, 55]], dtype=int32),
 array([[40, 86, 90, 50, 71, 21, 88, 39, 51, 63, 78],
        [62, 35, 84, 57, 46, 71, 11, 68, 53, 79, 29]], dtype=int32),
 array([[22, 49, 61, 66, 94, 41, 15, 25, 38, 92, 30],
        [76, 56, 77, 27, 65, 87, 52, 39, 80, 47, 33]], dtype=int32)]