In [1]:
import numpy as np

In [19]:
matriz = np.random.randint(1, 20, size=(5,5))
min = np.min(matriz)
max = np.max(matriz)

print(matriz)

print(min)
print(max)

matriz[matriz < 10] = 0
print(matriz)


[[17 14 14 11 14]
 [ 7  8  3  5 13]
 [ 1  6  7 17 12]
 [ 2  6 14  6 14]
 [17  3  4 15 17]]
1
17
[[17 14 14 11 14]
 [ 0  0  0  0 13]
 [ 0  0  0 17 12]
 [ 0  0 14  0 14]
 [17  0  0 15 17]]


In [20]:
arr1_sum = np.sum(matriz[0, :])
arr2_sum = np.sum(matriz[1, :])
arr3_sum = np.sum(matriz[2, :])
arr4_sum = np.sum(matriz[3, :])
arr5_sum = np.sum(matriz[4, :])

print(arr1_sum)
print(arr2_sum)
print(arr3_sum)
print(arr4_sum)
print(arr5_sum)

70
13
29
28
49


In [25]:
soma_linhas = np.sum(matriz, axis=1)
print(soma_linhas)

soma_colunas = np.sum(matriz, axis=0)
print(soma_colunas)

[70 13 29 28 49]
[34 14 28 43 70]


In [ ]:
media1 = np.mean(matriz)
print(media1)

media2 = np.sum(matriz) / matriz.size # Usar len() se for array 1D e .size se for 2D+
print(media2)

7.56
7.56
